input {
  kafka {
    bootstrap_servers => "10.0.1.4:9092"
    topics => ["ssh-logs", "process-logs", "network-logs", "windows-logs" ]
    codec => "json"
    group_id => "logstash-consumer"
  }
}

filter {
  # Add hostname for tracking
  mutate {
    add_field => { "[@metadata][pipeline]" => "kafka-pipeline" }
  }
  
  # Parse JSON if it's in the message field
  if [message] =~ /^\{.*\}$/ {
    json {
      source => "message"
    }
  }
}

output {
  elasticsearch {
    hosts => ["10.0.1.2:9200"]
    index => "soc-logs-%{+YYYY.MM.dd}"
    user => "elastic"
    password => "EsWdmp_QKR=NJzO4jDVU"
  }
  
  # Also output to console for debugging
  stdout {
    codec => rubydebug
  }
}
